function DetailedReport({
  showReport,
  setShowReport,
  result,
}) {

  if (!showReport || !result)
    return null;

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        background:
          "rgba(0,0,0,0.8)",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        zIndex: 9999,
      }}
    >
      <div
        style={{
          width: "90%",
          maxWidth: "900px",
          background: "#0f172a",
          borderRadius: "30px",
          padding: "40px",
          color: "white",
          maxHeight: "85vh",
          overflowY: "auto",
        }}
      >
        <h1
          style={{
            marginBottom: "30px",
            textAlign: "center",
          }}
        >
          Detailed Analysis Report
        </h1>

        <div
          style={{
            display: "grid",
            gridTemplateColumns:
              "repeat(auto-fit,minmax(220px,1fr))",
            gap: "20px",
          }}
        >
          <ReportCard
            title="Plagiarism"
            value={`${result.plagiarism_score}%`}
          />

          <ReportCard
            title="Originality"
            value={`${result.originality_score}%`}
          />

          <ReportCard
            title="Grammar"
            value={`${result.grammar_score}%`}
          />

          <ReportCard
            title="AI Score"
            value={`${result.ai_score}%`}
          />
        </div>

        <div
          style={{
            marginTop: "30px",
            background: "#020617",
            padding: "25px",
            borderRadius: "20px",
          }}
        >
          <h3
            style={{
              color: "#38bdf8",
              marginBottom: "15px",
            }}
          >
            Summary
          </h3>

          <p
            style={{
              color: "#cbd5e1",
              lineHeight: "30px",
            }}
          >
            This document was analyzed for
            plagiarism, originality,
            writing quality and overall
            content structure. The scores
            above represent the current
            assessment generated by the
            system.
          </p>
        </div>

        <button
          onClick={() =>
            setShowReport(false)
          }
          style={{
            width: "100%",
            marginTop: "30px",
            padding: "18px",
            border: "none",
            borderRadius: "18px",
            background:
              "linear-gradient(90deg,#38bdf8,#7c3aed)",
            color: "white",
            fontWeight: "bold",
            cursor: "pointer",
          }}
        >
          Close Report
        </button>
      </div>
    </div>
  );
}

function ReportCard({
  title,
  value,
}) {
  return (
    <div
      style={{
        background: "#020617",
        padding: "25px",
        borderRadius: "20px",
        textAlign: "center",
      }}
    >
      <h2>{title}</h2>

      <h1
        style={{
          color: "#38bdf8",
          marginTop: "15px",
        }}
      >
        {value}
      </h1>
    </div>
  );
}

export default DetailedReport;